<a href="https://colab.research.google.com/github/sandeep0097-97/RoomanDa/blob/main/numpyassignmentsolution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####1. How do you create a NumPy array from a Python list?

####Question: Convert the Python list [1, 2, 3, 4, 5] into a NumPy array.



In [12]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)


[1 2 3 4 5]


####2. How do you create a 3×3 matrix filled with zeros?

####Question: Create a 3×3 NumPy array filled with zeros.



In [13]:
arr = np.zeros((3, 3))
print(arr)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


####3. How do you generate a NumPy array with values from 1 to 10?

####Question: Create an array with numbers from 1 to 10.



In [14]:
arr = np.arange(1, 11)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


####4. How do you create a NumPy array of equally spaced values?

####Question: Create an array of 5 numbers between 0 and 1.



In [15]:
arr = np.linspace(0, 1, 5)
print(arr)


[0.   0.25 0.5  0.75 1.  ]


####5. How do you reshape a NumPy array?

####Question: Convert a 1D array [1, 2, 3, 4, 5, 6] into a 2×3 matrix.



In [16]:
arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


####6. How do you perform element-wise addition on NumPy arrays?

####Question: Given arr1 = [1, 2, 3] and arr2 = [4, 5, 6], perform element-wise addition.

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)


[5 7 9]


####7. How do you find the maximum and minimum values in a NumPy array?

####Question: Find the maximum and minimum values in the array [3, 7, 2, 9, 5].



In [18]:
arr = np.array([3, 7, 2, 9, 5])
max_value = np.max(arr)
min_value = np.min(arr)
print("Max:", max_value)
print("Min:", min_value)


Max: 9
Min: 2


####8. How do you calculate the mean and standard deviation of a NumPy array?

####Question: Compute the mean and standard deviation of [10, 20, 30, 40, 50].



####9. How do you filter elements from a NumPy array?


####Question: Extract all values greater than 4 from the array [1, 3, 5, 7, 9].



####9. How do you filter elements from a NumPy array?


In [19]:
arr = np.array([1, 3, 5, 7, 9])
filtered_arr = arr[arr > 4]
print(filtered_arr)


[5 7 9]


####Question: Multiply two matrices:

lua
Copy
Edit


####10. How do you perform matrix multiplication in NumPy?

In [20]:
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]


In [21]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
result = np.dot(A, B)
print(result)


[[19 22]
 [43 50]]
